[build]
target_dir = "dist"
public_url = "/"

[serve]
addresses = ["127.0.0.1"]
port = 8803
open = false

[watch]
features = []
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["src"]

# Tailwind is configured via index.html <link data-trunk rel="tailwind-css" ...>
